### ISSUE TITLE
stash problem

### ISSUE THREAD

**Issue by aymaneH** [aymaneH/omega#3]
Here https://github.com/aymaneH/omega/blob/master/src/public/style.css#L3
Here https://github.com/aymaneH/omega/blob/master/src/public/style.css#L9
and here https://github.com/aymaneH/omega/blob/master/src/public/style.css#L19
 you can see that after stash we have additional lines ! they should be remouved!

**Comment by aymaneH** [comment]
@Touza  just remove those lines and push

**Comment by Touza** [comment]
so we have to delete these lines from the file that we stash

**Comment by aymaneH** [comment]
Yes that's it
